// Real Odoo implementation partners, sourced from Odoo's official public
// partner directory at https://www.odoo.com/partners (fetched Oct 2026).
// Each entry links to the company's genuine Odoo profile page, which carries
// the official contact / reference details for that partner.
const PARTNERS = [
  // ---------------- India ----------------
  { name: "Oodu Implementers Private Limited", country: "India", tier: "Gold", path: "/partners/oodu-implementers-private-limited-2199251" },
  { name: "Softhealer Technologies Private Limited", country: "India", tier: "Gold", path: "/partners/softhealer-technologies-private-limited-13363635" },
  { name: "Emipro Technologies Private Limited", country: "India", tier: "Gold", path: "/partners/emipro-technologies-private-limited-32230995" },
  { name: "Ksolves India Ltd.", country: "India", tier: "Gold", path: "/partners/ksolves-india-ltd-6069511" },
  { name: "Browseinfo", country: "India", tier: "Gold", path: "/partners/browseinfo-3162744" },
  { name: "TechUltra Solutions Pvt. Ltd.", country: "India", tier: "Gold", path: "/partners/techultra-solutions-pvt-ltd-3953642" },
  { name: "Teckzilla Technologies", country: "India", tier: "Gold", path: "/partners/teckzilla-technologies-12578977" },
  { name: "Serpent Consulting Services Pvt. Ltd.", country: "India", tier: "Gold", path: "/partners/serpent-consulting-services-pvt-ltd-160703" },
  { name: "Caret IT Solutions Pvt. Ltd.", country: "India", tier: "Gold", path: "/partners/caret-it-solutions-pvt-ltd-2036036" },
  { name: "Closyss Technologies LLP", country: "India", tier: "Gold", path: "/partners/closyss-technologies-llp-13254479" },
  { name: "Navabrind IT Solutions Pvt Ltd", country: "India", tier: "Gold", path: "/partners/navabrind-it-solutions-pvt-ltd-697848" },
  { name: "Mindphin Technologies Pvt. Ltd.", country: "India", tier: "Silver", path: "/partners/mindphin-technologies-pvt-ltd-10727770" },
  { name: "Prixgen Tech Solutions Private Limited", country: "India", tier: "Silver", path: "/partners/prixgen-tech-solutions-private-limited-1450290" },
  { name: "Cybrosys Techno Solutions Pvt.Ltd", country: "India", tier: "Silver", path: "/partners/cybrosys-techno-solutions-pvt-ltd-759167" },
  { name: "WEBKUL SOFTWARE PVT LTD", country: "India", tier: "Silver", path: "/partners/webkul-software-pvt-ltd-13619" },
  { name: "Warlock Technologies Pvt Ltd", country: "India", tier: "Silver", path: "/partners/warlock-technologies-pvt-ltd-3435649" },
  { name: "SYGMETIV PRIVATE LIMITED", country: "India", tier: "Silver", path: "/partners/sygmetiv-private-limited-13054239" },
  { name: "CandidRoot Solutions Private Limited", country: "India", tier: "Silver", path: "/partners/candidroot-solutions-private-limited-4509632" },
  { name: "Kanak Infosystems LLP", country: "India", tier: "Silver", path: "/partners/kanak-infosystems-llp-19492" },
  { name: "Technogeo Soft Solution Pvt. Ltd", country: "India", tier: "Silver", path: "/partners/technogeo-soft-solution-pvt-ltd-1186628" },
  { name: "Almighty Consulting Solutions Pvt. Ltd.", country: "India", tier: "Silver", path: "/partners/almighty-consulting-solutions-pvt-ltd-6058653" },
  { name: "INSOFT.COM PRIVATE LIMITED", country: "India", tier: "Silver", path: "/partners/insoft-com-private-limited-11952816" },
  { name: "LINKS4ENGG INDIA PRIVATE LIMITED", country: "India", tier: "Silver", path: "/partners/links4engg-india-private-limited-16316004" },
  { name: "TheERPbot", country: "India", tier: "Silver", path: "/partners/theerpbot-19503268" },
  { name: "Globalteckz", country: "India", tier: "Silver", path: "/partners/globalteckz-653869" },
  { name: "Tatvamasi Labs", country: "India", tier: "Silver", path: "/partners/tatvamasi-labs-12326722" },
  { name: "Evozard Consulting Services Private Limited", country: "India", tier: "Silver", path: "/partners/evozard-consulting-services-private-limited-3847147" },
  { name: "NAMAH SOFTECH PRIVATE LIMITED", country: "India", tier: "Silver", path: "/partners/namah-softech-private-limited-16781468" },
  { name: "AGBE Technology Solutions Private Limited", country: "India", tier: "Silver", path: "/partners/agbe-technology-solutions-private-limited-28616718" },
  { name: "BROADTECH IT SOLUTIONS PRIVATE LIMITED", country: "India", tier: "Silver", path: "/partners/broadtech-it-solutions-private-limited-17556068" },
  { name: "PINNACLE SEVEN TECHNOLOGIES PRIVATE LIMITED", country: "India", tier: "Silver", path: "/partners/pinnacle-seven-technologies-private-limited-7624178" },
  { name: "Synodica Solutions Pvt. Ltd.", country: "India", tier: "Silver", path: "/partners/synodica-solutions-pvt-ltd-5985053" },
  { name: "Linescripts Softwares Pvt. Ltd.", country: "India", tier: "Silver", path: "/partners/linescripts-softwares-pvt-ltd-9584428" },
  { name: "7 dot 2 IT Consulting", country: "India", tier: "Silver", path: "/partners/7-dot-2-it-consulting-18341560" },
  { name: "Primacy Infotech Private Limited", country: "India", tier: "Silver", path: "/partners/primacy-infotech-private-limited-8850840" },
  { name: "S3N CONSULTING SERVICES (OPC) PRIVATE LIMITED", country: "India", tier: "Silver", path: "/partners/s3n-consulting-services-opc-private-limited-19883773" },
  { name: "Highshine IT Solutions Private Limited", country: "India", tier: "Silver", path: "/partners/highshine-it-solutions-private-limited-15925862" },
  { name: "Master Software Solutions", country: "India", tier: "Silver", path: "/partners/master-software-solutions-17131656" },
  { name: "NAKSHATRA SALES & SERVICES", country: "India", tier: "Silver", path: "/partners/nakshatra-sales-services-18634289" },
  { name: "Nioses Tech Private Limited", country: "India", tier: "Silver", path: "/partners/nioses-tech-private-limited-14303342" },
  { name: "2ISOLUTIONS CONSULTING SERVICES PRIVATE LIMITED", country: "India", tier: "Silver", path: "/partners/2isolutions-consulting-services-private-limited-15682886" },
  { name: "BeyonData Solutions Pvt Ltd", country: "India", tier: "Silver", path: "/partners/beyondata-solutions-pvt-ltd-1517713" },
  { name: "GURUEBS TECH CONSULTING PRIVATE LIMITED", country: "India", tier: "Silver", path: "/partners/guruebs-tech-consulting-private-limited-29763077" },
  { name: "Ahex Technologies Private Limited", country: "India", tier: "Silver", path: "/partners/ahex-technologies-private-limited-12409666" },
  { name: "SunArc Technologies", country: "India", tier: "Silver", path: "/partners/sunarc-technologies-251938" },
  { name: "Cloudmonte Technologies Pvt Ltd", country: "India", tier: "Silver", path: "/partners/cloudmonte-technologies-pvt-ltd-11449715" },
  { name: "QWY SOFTWARE PRIVATE LIMITED", country: "India", tier: "Silver", path: "/partners/qwy-software-private-limited-15572188" },
  { name: "Areterix Technologies LLP", country: "India", tier: "Silver", path: "/partners/areterix-technologies-llp-6220077" },
  { name: "Auxintech Cloud Solutions Private Limited", country: "India", tier: "Silver", path: "/partners/auxintech-cloud-solutions-private-limited-2624957" },
  { name: "Banibro Technologies Pvt Ltd.", country: "India", tier: "Silver", path: "/partners/banibro-technologies-pvt-ltd-31532511" },
  { name: "RANMAN LABS", country: "India", tier: "Silver", path: "/partners/ranman-labs-20454301" },
  { name: "GSUS Star Software Solutions Private Limited", country: "India", tier: "Silver", path: "/partners/gsus-star-software-solutions-private-limited-20189841" },
  { name: "New Horizons Cybersoft Ltd", country: "India", tier: "Silver", path: "/partners/new-horizons-cybersoft-ltd-1924123" },
  { name: "EMERGING ALLIANCE", country: "India", tier: "Silver", path: "/partners/emerging-alliance-18470276" },
  { name: "FEGNO TECHNOLOGIES LLP", country: "India", tier: "Silver", path: "/partners/fegno-technologies-llp-3264329" },
  { name: "Kavi Software Technologies Pvt Ltd", country: "India", tier: "Silver", path: "/partners/kavi-software-technologies-pvt-ltd-17174193" },
  { name: "TECHMATIC SYSTEMS INDIA PRIVATE LIMITED", country: "India", tier: "Silver", path: "/partners/techmatic-systems-india-private-limited-14930407" },
  { name: "EvvoTech", country: "India", tier: "Silver", path: "/partners/evvotech-20612275" },
  { name: "APP Infoweb Private Limited", country: "India", tier: "Silver", path: "/partners/app-infoweb-private-limited-6598120" },
  { name: "Ontash India Technologies Private Limited", country: "India", tier: "Silver", path: "/partners/ontash-india-technologies-private-limited-28892359" },
  { name: "CLOUDSCIENCE LABS PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/cloudscience-labs-private-limited-15692380" },
  { name: "XBP Asia Technologies Private Limited", country: "India", tier: "Silver", path: "/partners/xbp-asia-technologies-private-limited-16369295" },
  { name: "ATHARVA SYSTEM", country: "India", tier: "Ready", path: "/partners/atharva-system-842672" },
  { name: "Ascetic Business Solution LLP", country: "India", tier: "Ready", path: "/partners/ascetic-business-solution-llp-1182648" },
  { name: "SETU CONSULTING SERVICES PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/setu-consulting-services-private-limited-6391581" },
  { name: "Braincrew Apps", country: "India", tier: "Ready", path: "/partners/braincrew-apps-789392" },
  { name: "TECHNAUREUS INFO SOLUTIONS PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/technaureus-info-solutions-private-limited-17634561" },
  { name: "TeqStars Technologies", country: "India", tier: "Ready", path: "/partners/teqstars-technologies-1525023" },
  { name: "Reliution", country: "India", tier: "Ready", path: "/partners/reliution-7443555" },
  { name: "Uncanny Consulting Services LLP", country: "India", tier: "Ready", path: "/partners/uncanny-consulting-services-llp-3959532" },
  { name: "Veevee Infotech", country: "India", tier: "Ready", path: "/partners/veevee-infotech-18115608" },
  { name: "INFINTOR SOLUTIONS LLP", country: "India", tier: "Ready", path: "/partners/infintor-solutions-llp-8973246" },
  { name: "PRASHANT DINDAYAL POPALI", country: "India", tier: "Ready", path: "/partners/prashant-dindayal-popali-16603179" },
  { name: "ERP Harbor Consulting Services", country: "India", tier: "Ready", path: "/partners/erp-harbor-consulting-services-2753502" },
  { name: "HMRC INDUSTRY PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/hmrc-industry-private-limited-13374057" },
  { name: "Surekha Technologies Pvt. Ltd.", country: "India", tier: "Ready", path: "/partners/surekha-technologies-pvt-ltd-4715165" },
  { name: "ASCENSIVE TECHNOLOGIES LLP", country: "India", tier: "Ready", path: "/partners/ascensive-technologies-llp-1470548" },
  { name: "TECHOSOFT SOLUTIONS (OPC) PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/techosoft-solutions-opc-private-limited-21373568" },
  { name: "7Span Internet Private Limited", country: "India", tier: "Ready", path: "/partners/7span-internet-private-limited-13438906" },
  { name: "BOTSPOT INFOWARE PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/botspot-infoware-private-limited-14205336" },
  { name: "BIZTECH IT CONSULTANCY PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/biztech-it-consultancy-private-limited-12505897" },
  { name: "DeckSpectra Technologies LLP", country: "India", tier: "Ready", path: "/partners/deckspectra-technologies-llp-16622404" },
  { name: "FINABLE CONSULTING PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/finable-consulting-private-limited-21110754" },
  { name: "KODERXPERT TECHNOLOGIES PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/koderxpert-technologies-private-limited-32097847" },
  { name: "Akarigo India", country: "India", tier: "Ready", path: "/partners/akarigo-india-21385689" },
  { name: "Appx IT Consultancy LLP", country: "India", tier: "Ready", path: "/partners/appx-it-consultancy-llp-12354630" },
  { name: "ERP INNATE", country: "India", tier: "Ready", path: "/partners/erp-innate-30621374" },
  { name: "FADEL SOFTWARE SOLUTIONS PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/fadel-software-solutions-private-limited-17408905" },
  { name: "Heliconia Solutions Pvt. Ltd.", country: "India", tier: "Ready", path: "/partners/heliconia-solutions-pvt-ltd-1063969" },
  { name: "Icon TechSoft Pvt. Ltd.", country: "India", tier: "Ready", path: "/partners/icon-techsoft-pvt-ltd-17628686" },
  { name: "Jupical Technologies Pvt. Ltd.", country: "India", tier: "Ready", path: "/partners/jupical-technologies-pvt-ltd-14077236" },
  { name: "Prime Minds Consulting Private Limited", country: "India", tier: "Ready", path: "/partners/prime-minds-consulting-private-limited-1875204" },
  { name: "Synconics Technologies Pvt. Ltd.", country: "India", tier: "Ready", path: "/partners/synconics-technologies-pvt-ltd-626268" },
  { name: "iFenSys InfoTech Private Limited", country: "India", tier: "Ready", path: "/partners/ifensys-infotech-private-limited-6087300" },
  { name: "FLOWEAZY SOFTWARE SOLUTIONS LLP", country: "India", tier: "Ready", path: "/partners/floweazy-software-solutions-llp-15157785" },
  { name: "TARGET INTEGRATION CONSULTANCY PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/target-integration-consultancy-private-limited-12045620" },
  { name: "Absolin Software Solutions LLP", country: "India", tier: "Ready", path: "/partners/absolin-software-solutions-llp-1063068" },
  { name: "Shadail Technology Private Limited", country: "India", tier: "Ready", path: "/partners/shadail-technology-private-limited-5589802" },
  { name: "Silver Touch Technologies Ltd.", country: "India", tier: "Ready", path: "/partners/silver-touch-technologies-ltd-2751460" },
  { name: "Spellbound Soft Solutions", country: "India", tier: "Ready", path: "/partners/spellbound-soft-solutions-6050846" },
  { name: "Tenth Planet Technologies- India", country: "India", tier: "Ready", path: "/partners/tenth-planet-technologies-india-1008586" },
  { name: "Trivecta Digital Solutions Private Limited", country: "India", tier: "Ready", path: "/partners/trivecta-digital-solutions-private-limited-16406333" },
  { name: "Webrulers Infotech LLP", country: "India", tier: "Ready", path: "/partners/webrulers-infotech-llp-27449037" },
  { name: "ABBLEZ TECHNOLOGIES AND ROBOTICS LLP", country: "India", tier: "Ready", path: "/partners/abblez-technologies-and-robotics-llp-14617914" },
  { name: "ALPHA DEZINE SERVICES PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/alpha-dezine-services-private-limited-27009073" },
  { name: "CAPTIVEA SOFTWARE PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/captivea-software-private-limited-22732155" },
  { name: "DX8 TECHNOLOGIES PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/dx8-technologies-private-limited-20719831" },
  { name: "Digital Order Technology Private Limited", country: "India", tier: "Ready", path: "/partners/digital-order-technology-private-limited-24447312" },
  { name: "Greytrix", country: "India", tier: "Ready", path: "/partners/greytrix-17221548" },
  { name: "HTIC Global", country: "India", tier: "Ready", path: "/partners/htic-global-13302265" },
  { name: "PREFORTUNE TECHNOLOGIES LIMITED LIABILITY PARTNERSHIP", country: "India", tier: "Ready", path: "/partners/prefortune-technologies-limited-liability-partnership-17884479" },
  { name: "SA PODIT Services LLP", country: "India", tier: "Ready", path: "/partners/sa-podit-services-llp-15156467" },
  { name: "TECHVOOT SOLUTIONS", country: "India", tier: "Ready", path: "/partners/techvoot-solutions-18298112" },
  { name: "Alligator Infosoft", country: "India", tier: "Ready", path: "/partners/alligator-infosoft-14162639" },
  { name: "Aspireal Technologies Pvt. Ltd.", country: "India", tier: "Ready", path: "/partners/aspireal-technologies-pvt-ltd-2067229" },
  { name: "Galaxy Weblinks Limited.", country: "India", tier: "Ready", path: "/partners/galaxy-weblinks-limited-7185115" },
  { name: "Leofren Technologies", country: "India", tier: "Ready", path: "/partners/leofren-technologies-12742967" },
  { name: "Skyscend Business Solutions Pvt. Ltd.", country: "India", tier: "Ready", path: "/partners/skyscend-business-solutions-pvt-ltd-3844640" },
  { name: "Aktiv Software Pvt. Ltd.", country: "India", tier: "Ready", path: "/partners/aktiv-software-pvt-ltd-13055881" },
  { name: "CRYSTALDATA SOFTWARE SERVICES INDIA PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/crystaldata-software-services-india-private-limited-16559897" },
  { name: "Mordant Business Solutions", country: "India", tier: "Ready", path: "/partners/mordant-business-solutions-10043411" },
  { name: "SYMAKE SOLUTIONS PVT LTD", country: "India", tier: "Ready", path: "/partners/symake-solutions-pvt-ltd-33394598" },
  { name: "SoftPrime Consulting Private Limited", country: "India", tier: "Ready", path: "/partners/softprime-consulting-private-limited-12007448" },
  { name: "UNISAS ITBUSINESS SOLUTIONS PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/unisas-itbusiness-solutions-private-limited-18214147" },
  { name: "DREAMZ TECH SOLUTIONS PVT LTD", country: "India", tier: "Ready", path: "/partners/dreamz-tech-solutions-pvt-ltd-11668078" },
  { name: "ENTERPRISE SYSTEM SOLUTIONS PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/enterprise-system-solutions-private-limited-13261208" },
  { name: "FLEXSIN TECHNOLOGIES", country: "India", tier: "Ready", path: "/partners/flexsin-technologies-14784107" },
  { name: "IPROGRAMMER SOLUTIONS PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/iprogrammer-solutions-private-limited-1457547" },
  { name: "Sada Smart Solutions LLP", country: "India", tier: "Ready", path: "/partners/sada-smart-solutions-llp-6971903" },
  { name: "TEFUGEN TECHNOLOGIES PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/tefugen-technologies-private-limited-13872645" },
  { name: "5Lobes Technologies Private Limited", country: "India", tier: "Ready", path: "/partners/5lobes-technologies-private-limited-20253898" },
  { name: "Client Linx Software Private Ltd", country: "India", tier: "Ready", path: "/partners/client-linx-software-private-ltd-19907600" },
  { name: "Engage & Reap Technologies Private Limited", country: "India", tier: "Ready", path: "/partners/engage-reap-technologies-private-limited-18079887" },
  { name: "Gritxi Technologies Pvt. Ltd.", country: "India", tier: "Ready", path: "/partners/gritxi-technologies-pvt-ltd-15046478" },
  { name: "HASHSTUDIOZ TECHNOLOGIES PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/hashstudioz-technologies-private-limited-26708169" },
  { name: "Intech Creative Services Pvt Ltd", country: "India", tier: "Ready", path: "/partners/intech-creative-services-pvt-ltd-23359111" },
  { name: "JMR INFOTECH INDIA PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/jmr-infotech-india-private-limited-15342560" },
  { name: "Nichi-In Software Solutions Pvt. Ltd.", country: "India", tier: "Ready", path: "/partners/nichi-in-software-solutions-pvt-ltd-7731567" },
  { name: "Pragmatic Techsoft Pvt Ltd", country: "India", tier: "Ready", path: "/partners/pragmatic-techsoft-pvt-ltd-1254750" },
  { name: "Prism IT Solutions Private Limited", country: "India", tier: "Ready", path: "/partners/prism-it-solutions-private-limited-20679295" },
  { name: "TECHSOFYA DIGITAL PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/techsofya-digital-private-limited-30571217" },
  { name: "THAPOVAN INFO SYSTEMS PVT", country: "India", tier: "Ready", path: "/partners/thapovan-info-systems-pvt-16932461" },
  { name: "AAKORYX GLOBAL SOLUTIONS LLP", country: "India", tier: "Ready", path: "/partners/aakoryx-global-solutions-llp-26854719" },
  { name: "Ayeze Comvision Technologies Private Limited", country: "India", tier: "Ready", path: "/partners/ayeze-comvision-technologies-private-limited-26329478" },
  { name: "DHECODED AI PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/dhecoded-ai-private-limited-32618705" },
  { name: "ECHOBITZ IT SOLUTIONS PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/echobitz-it-solutions-private-limited-18224246" },
  { name: "Everow Advisors LLP", country: "India", tier: "Ready", path: "/partners/everow-advisors-llp-30580650" },
  { name: "GREY SPACE COMPUTING PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/grey-space-computing-private-limited-27840890" },
  { name: "INTECHUAL SOLUTIONS", country: "India", tier: "Ready", path: "/partners/intechual-solutions-7450489" },
  { name: "MAIFELZ TECHNOLOGIES LLP", country: "India", tier: "Ready", path: "/partners/maifelz-technologies-llp-34879090" },
  { name: "NEXUSEPM CONSULTING PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/nexusepm-consulting-private-limited-27035836" },
  { name: "QUADRIC INFORMATION TECHNOLOGY PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/quadric-information-technology-private-limited-19229442" },
  { name: "RIGHT ANGLE SOLUTIONS", country: "India", tier: "Ready", path: "/partners/right-angle-solutions-21408563" },
  { name: "SKYNET GLOBAL SYSTEMS", country: "India", tier: "Ready", path: "/partners/skynet-global-systems-31046035" },
  { name: "SynapseIndia Outsourcing Pvt. Ltd.", country: "India", tier: "Ready", path: "/partners/synapseindia-outsourcing-pvt-ltd-10370484" },
  { name: "TIMUS CONSULTING SERVICES (OPC) PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/timus-consulting-services-opc-private-limited-17224874" },
  { name: "TROOTECH BUSINESS SOLUTIONS PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/trootech-business-solutions-private-limited-31902139" },
  { name: "VAYASOFT SOLUTIONS PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/vayasoft-solutions-private-limited-18372375" },
  { name: "DELOITTE TOUCHE TOHMATSU INDIA LLP", country: "India", tier: "Ready", path: "/partners/deloitte-touche-tohmatsu-india-llp-21082654" },
  { name: "EARBOR LLP", country: "India", tier: "Ready", path: "/partners/earbor-llp-25835898" },
  { name: "EGUARDIAN GLOBAL SERVICES INDIA PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/eguardian-global-services-india-private-limited-21881995" },
  { name: "EXATO TECHNOLOGIES LIMITED", country: "India", tier: "Ready", path: "/partners/exato-technologies-limited-23188667" },
  { name: "GLOBALS ITES PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/globals-ites-private-limited-30021843" },
  { name: "GLOBX DIGITAL LLP", country: "India", tier: "Ready", path: "/partners/globx-digital-llp-31867354" },
  { name: "GeNNxt Technologies Pvt. Ltd.", country: "India", tier: "Ready", path: "/partners/gennxt-technologies-pvt-ltd-33760260" },
  { name: "KORECENT SOLUTIONS PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/korecent-solutions-private-limited-19007378" },
  { name: "MAGNETO IT SOLUTIONS PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/magneto-it-solutions-private-limited-27286875" },
  { name: "MAINSTAY NEXT PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/mainstay-next-private-limited-25408072" },
  { name: "Nikqik Technologies Private Limited", country: "India", tier: "Ready", path: "/partners/nikqik-technologies-private-limited-13855640" },
  { name: "Nliven Technologies", country: "India", tier: "Ready", path: "/partners/nliven-technologies-24554439" },
  { name: "PHENOM CLOUD INDIA PRIVATE LIMITED", country: "India", tier: "Ready", path: "/partners/phenom-cloud-india-private-limited-24361344" },
  { name: "PHYTEC EMBEDDED PVT LTD", country: "India", tier: "Ready", path: "/partners/phytec-embedded-pvt-ltd-18346606" },
  { name: "SpurTree Technologies Pvt. Ltd.", country: "India", tier: "Ready", path: "/partners/spurtree-technologies-pvt-ltd-25024669" },

  // ---------------- United States ----------------
  { name: "Bista Solutions Inc.", country: "United States", tier: "Gold", path: "/partners/bista-solutions-inc-3994" },
  { name: "Gray Matter Logic", country: "United States", tier: "Gold", path: "/partners/gray-matter-logic-1288477" },
  { name: "QOC Innovations", country: "United States", tier: "Gold", path: "/partners/qoc-innovations-3165929" },
  { name: "Captivea USA", country: "United States", tier: "Gold", path: "/partners/captivea-usa-1489395" },
  { name: "Novobi", country: "United States", tier: "Gold", path: "/partners/novobi-481144" },
  { name: "Cudio Inc.", country: "United States", tier: "Gold", path: "/partners/cudio-inc-12127425" },
  { name: "Brainvire Infotech Inc.", country: "United States", tier: "Gold", path: "/partners/brainvire-infotech-inc-2046862" },
  { name: "S4 Solutions", country: "United States", tier: "Gold", path: "/partners/s4-solutions-1918117" },
  { name: "Bay Forward LLC", country: "United States", tier: "Silver", path: "/partners/bay-forward-llc-22531546" },
  { name: "Systems Services, Inc.", country: "United States", tier: "Silver", path: "/partners/systems-services-inc-2038095" },
  { name: "Reach Concept", country: "United States", tier: "Silver", path: "/partners/reach-concept-1759763" },
  { name: "Talus ERP", country: "United States", tier: "Silver", path: "/partners/talus-erp-2797963" },
  { name: "Sodexis, Inc.", country: "United States", tier: "Silver", path: "/partners/sodexis-inc-22634" },
  { name: "Hamdek", country: "United States", tier: "Silver", path: "/partners/hamdek-25730256" },
  { name: "Hibou Corp.", country: "United States", tier: "Silver", path: "/partners/hibou-corp-734837" },
  { name: "Tekgenio", country: "United States", tier: "Silver", path: "/partners/tekgenio-11262147" },
  { name: "Rooteam", country: "United States", tier: "Silver", path: "/partners/rooteam-1894890" },
  { name: "DFW IT Partner LLC", country: "United States", tier: "Silver", path: "/partners/dfw-it-partner-llc-10956187" },
  { name: "OBS Solutions Inc.", country: "United States", tier: "Silver", path: "/partners/obs-solutions-inc-3592202" },
  { name: "NC Automation", country: "United States", tier: "Silver", path: "/partners/nc-automation-17348456" },
  { name: "O2B Technologies", country: "United States", tier: "Ready", path: "/partners/o2b-technologies-1842223" },

  // ---------------- United Kingdom ----------------
  { name: "Smart Information Technologies Ltd", country: "United Kingdom", tier: "Gold", path: "/partners/smart-information-technologies-ltd-442178" },
  { name: "Sapentia", country: "United Kingdom", tier: "Gold", path: "/partners/sapentia-34384804" },
  { name: "Target Integration, UK", country: "United Kingdom", tier: "Gold", path: "/partners/target-integration-uk-4246220" },
  { name: "Gravitai UK", country: "United Kingdom", tier: "Gold", path: "/partners/gravitai-uk-3852902" },
  { name: "InFlow Systems", country: "United Kingdom", tier: "Gold", path: "/partners/inflow-systems-12590912" },
  { name: "Akarigo Ltd", country: "United Kingdom", tier: "Silver", path: "/partners/akarigo-ltd-1882307" },
  { name: "Amaroo Solutions Limited", country: "United Kingdom", tier: "Silver", path: "/partners/amaroo-solutions-limited-1390726" },
  { name: "Business Calibration Limited", country: "United Kingdom", tier: "Silver", path: "/partners/business-calibration-limited-7259353" },
  { name: "MUCH. CONSULTING LTD", country: "United Kingdom", tier: "Silver", path: "/partners/much-consulting-ltd-16152414" },
  { name: "Sixo Systems", country: "United Kingdom", tier: "Silver", path: "/partners/sixo-systems-20966669" },
  { name: "Techplus Solutions Ltd", country: "United Kingdom", tier: "Silver", path: "/partners/techplus-solutions-ltd-16659359" },

  // ---------------- Germany ----------------
  { name: "OBS Solutions GmbH", country: "Germany", tier: "Gold", path: "/partners/obs-solutions-gmbh-5889242" },
  { name: "openfellas GmbH", country: "Germany", tier: "Gold", path: "/partners/openfellas-gmbh-878799" },
  { name: "Intero Technologies GmbH", country: "Germany", tier: "Gold", path: "/partners/intero-technologies-gmbh-4364" },
  { name: "much. GmbH", country: "Germany", tier: "Gold", path: "/partners/much-gmbh-2228935" },
  { name: "manaTec GmbH", country: "Germany", tier: "Gold", path: "/partners/manatec-gmbh-1023999" },
  { name: "SH Digital Starten GmbH", country: "Germany", tier: "Gold", path: "/partners/sh-digital-starten-gmbh-10609718" },
  { name: "ODION GmbH", country: "Germany", tier: "Gold", path: "/partners/odion-gmbh-1566500" },
  { name: "Nexigo GmbH", country: "Germany", tier: "Gold", path: "/partners/nexigo-gmbh-16085640" },
  { name: "bloopark systems GmbH & Co. KG", country: "Germany", tier: "Gold", path: "/partners/bloopark-systems-gmbh-co-kg-218035" },
  { name: "braintec Deutschland", country: "Germany", tier: "Gold", path: "/partners/braintec-deutschland-137500" },
  { name: "ruhrdot GmbH", country: "Germany", tier: "Gold", path: "/partners/ruhrdot-gmbh-6985451" },
  { name: "Mate iT GmbH", country: "Germany", tier: "Gold", path: "/partners/mate-it-gmbh-24181352" },
  { name: "Peter Schwarz", country: "Germany", tier: "Silver", path: "/partners/peter-schwarz-1005494" },
  { name: "Hucke Media GmbH & Co. KG", country: "Germany", tier: "Silver", path: "/partners/hucke-media-gmbh-co-kg-6408454" },
  { name: "RATOCON GmbH", country: "Germany", tier: "Silver", path: "/partners/ratocon-gmbh-13069626" },
  { name: "rising systems AG", country: "Germany", tier: "Silver", path: "/partners/rising-systems-ag-69416" },
  { name: "HAV Media GmbH", country: "Germany", tier: "Silver", path: "/partners/hav-media-gmbh-6636097" },
  { name: "SAMSA-IT GmbH", country: "Germany", tier: "Silver", path: "/partners/samsa-it-gmbh-2438299" },
  { name: "Labiso GmbH", country: "Germany", tier: "Silver", path: "/partners/labiso-gmbh-9984829" },
  { name: "Quattro Consulting GmbH", country: "Germany", tier: "Silver", path: "/partners/quattro-consulting-gmbh-29853928" },

  // ---------------- United Arab Emirates ----------------
  { name: "Dow Group DMCC", country: "United Arab Emirates", tier: "Gold", path: "/partners/dow-group-dmcc-4937983" },
  { name: "Al Jawad Software House", country: "United Arab Emirates", tier: "Gold", path: "/partners/al-jawad-software-house-4598740" },
  { name: "OAKLAND - odooERP.ae", country: "United Arab Emirates", tier: "Gold", path: "/partners/oakland-odooerp-ae-1973969" },
  { name: "Hash Code IT Solutions", country: "United Arab Emirates", tier: "Gold", path: "/partners/hash-code-it-solutions-6561768" },
  { name: "Kaizen Principles", country: "United Arab Emirates", tier: "Gold", path: "/partners/kaizen-principles-8433600" },
  { name: "Fidobe Solutions LLC", country: "United Arab Emirates", tier: "Gold", path: "/partners/fidobe-solutions-llc-17550508" },
  { name: "Plennix Technologies (UAE)", country: "United Arab Emirates", tier: "Gold", path: "/partners/plennix-technologies-uae-6705458" },
  { name: "Plementus UAE", country: "United Arab Emirates", tier: "Gold", path: "/partners/plementus-uae-16745486" },
  { name: "VOXTRON MIDDLE EAST LLC", country: "United Arab Emirates", tier: "Gold", path: "/partners/voxtron-middle-east-llc-1942354" },
  { name: "Techbot", country: "United Arab Emirates", tier: "Silver", path: "/partners/techbot-4148604" },
  { name: "CODEX FOR INFORMATION TECHNOLOGY NETWORK SERVICES CO", country: "United Arab Emirates", tier: "Silver", path: "/partners/codex-for-information-technology-network-services-co-8188665" },
  { name: "Cloudmen", country: "United Arab Emirates", tier: "Silver", path: "/partners/cloudmen-9689666" },
  { name: "Adept Business Solution", country: "United Arab Emirates", tier: "Silver", path: "/partners/adept-business-solution-15604713" },
  { name: "EBTECH Technologies L.L.C", country: "United Arab Emirates", tier: "Silver", path: "/partners/ebtech-technologies-l-l-c-27261191" },
  { name: "Technova Information Technology L.L.C", country: "United Arab Emirates", tier: "Silver", path: "/partners/technova-information-technology-l-l-c-19881424" },
  { name: "AnaConEx IT Solutions L.L.C", country: "United Arab Emirates", tier: "Silver", path: "/partners/anaconex-it-solutions-l-l-c-9229739" },
  { name: "Uncanny Consulting Services FZC", country: "United Arab Emirates", tier: "Silver", path: "/partners/uncanny-consulting-services-fzc-17635990" },
  { name: "BIZTRAS INFORMATION TECHNOLOGY SOLUTIONS L.L.C.", country: "United Arab Emirates", tier: "Silver", path: "/partners/biztras-information-technology-solutions-l-l-c-5204287" },
  { name: "APPSGATE INFORMATION TECHNOLOGY L.L.C.", country: "United Arab Emirates", tier: "Silver", path: "/partners/appsgate-information-technology-l-l-c-15152842" },
  { name: "Brainvire Infotech - UAE", country: "United Arab Emirates", tier: "Silver", path: "/partners/brainvire-infotech-uae-24745151" },

  // ---------------- Canada ----------------
  { name: "E3K SOLUTIONS INC", country: "Canada", tier: "Gold", path: "/partners/e3k-solutions-inc-264615" },
  { name: "Arche TI", country: "Canada", tier: "Gold", path: "/partners/arche-ti-818719" },
  { name: "OERP Canada", country: "Canada", tier: "Gold", path: "/partners/oerp-canada-121744" },
  { name: "Odovia Integration", country: "Canada", tier: "Gold", path: "/partners/odovia-integration-11304128" },
  { name: "Syncoria", country: "Canada", tier: "Gold", path: "/partners/syncoria-1480761" },
  { name: "Bista Solutions Canada", country: "Canada", tier: "Gold", path: "/partners/bista-solutions-canada-847944" },
  { name: "QORELIS SOLUTIONS inc.", country: "Canada", tier: "Silver", path: "/partners/qorelis-solutions-inc-16104647" },
  { name: "Aphid Consulting, Inc.", country: "Canada", tier: "Silver", path: "/partners/aphid-consulting-inc-1574980" },
  { name: "Toews Consulting Inc.", country: "Canada", tier: "Silver", path: "/partners/toews-consulting-inc-5178874" },
  { name: "KerningCode Inc", country: "Canada", tier: "Silver", path: "/partners/kerningcode-inc-12371393" },
  { name: "Smart Information Technologies Ltd Canada", country: "Canada", tier: "Silver", path: "/partners/smart-information-technologies-ltd-canada-1826267" },
  { name: "Captivea Canada", country: "Canada", tier: "Silver", path: "/partners/captivea-canada-10652459" },
  { name: "AAZ Solutions", country: "Canada", tier: "Silver", path: "/partners/aaz-solutions-11606722" },
  { name: "NSI Canada", country: "Canada", tier: "Silver", path: "/partners/nsi-canada-19125146" },
  { name: "Ingeniu", country: "Canada", tier: "Silver", path: "/partners/ingeniu-2816327" },
  { name: "Kodershop North America", country: "Canada", tier: "Silver", path: "/partners/kodershop-north-america-10218995" },
  { name: "Lotus Beta Analytics", country: "Canada", tier: "Silver", path: "/partners/lotus-beta-analytics-5306737" },
  { name: "Kuantiik", country: "Canada", tier: "Ready", path: "/partners/kuantiik-4185003" },
  { name: "Blackware Technologies Inc.", country: "Canada", tier: "Ready", path: "/partners/blackware-technologies-inc-1060966" },
  { name: "Erp cloud llc", country: "Canada", tier: "Ready", path: "/partners/erp-cloud-llc-2065104" },

  // ---------------- Netherlands ----------------
  { name: "dooIT BV", country: "Netherlands", tier: "Gold", path: "/partners/dooit-bv-9823433" },
  { name: "Dynapps", country: "Netherlands", tier: "Gold", path: "/partners/dynapps-9050849" },
  { name: "360 ERP", country: "Netherlands", tier: "Gold", path: "/partners/360-erp-5224211" },
  { name: "Odoo Experts B.V.", country: "Netherlands", tier: "Gold", path: "/partners/odoo-experts-b-v-2063855" },
  { name: "Aardug", country: "Netherlands", tier: "Gold", path: "/partners/aardug-3508827" },
  { name: "Cravit", country: "Netherlands", tier: "Gold", path: "/partners/cravit-17881318" },
  { name: "Newway Solutions B.V.", country: "Netherlands", tier: "Gold", path: "/partners/newway-solutions-b-v-6174089" },
  { name: "Radical Fanatics", country: "Netherlands", tier: "Silver", path: "/partners/radical-fanatics-7076275" },
  { name: "Erp|open", country: "Netherlands", tier: "Silver", path: "/partners/erp-open-4357566" },
  { name: "WeSolved Group", country: "Netherlands", tier: "Silver", path: "/partners/wesolved-group-15679130" },
  { name: "KJ Software", country: "Netherlands", tier: "Silver", path: "/partners/kj-software-15755397" },
  { name: "Kilurion B.V.", country: "Netherlands", tier: "Silver", path: "/partners/kilurion-b-v-13521523" },
  { name: "Codeforward", country: "Netherlands", tier: "Silver", path: "/partners/codeforward-8944429" },
  { name: "Allinx", country: "Netherlands", tier: "Silver", path: "/partners/allinx-10791421" },
  { name: "ERP-M BV", country: "Netherlands", tier: "Silver", path: "/partners/erp-m-bv-2034556" },
  { name: "Liberated IT", country: "Netherlands", tier: "Silver", path: "/partners/liberated-it-16952745" },
  { name: "DAADIT B.V.", country: "Netherlands", tier: "Silver", path: "/partners/daadit-b-v-13736826" },
  { name: "MRNG", country: "Netherlands", tier: "Silver", path: "/partners/mrng-22831234" },
  { name: "Grip ICT BV", country: "Netherlands", tier: "Ready", path: "/partners/grip-ict-bv-1730383" },
  { name: "Blue Zebra", country: "Netherlands", tier: "Ready", path: "/partners/blue-zebra-3794631" },

  // ---------------- Australia ----------------
  { name: "WMSSoft Pty Ltd", country: "Australia", tier: "Gold", path: "/partners/wmssoft-pty-ltd-1161013" },
  { name: "WilldooIT", country: "Australia", tier: "Silver", path: "/partners/willdooit-951662" },
  { name: "WAO Group", country: "Australia", tier: "Silver", path: "/partners/wao-group-4192861" },
  { name: "Envertis (Div of Vision & Solutions Pty Ltd)", country: "Australia", tier: "Silver", path: "/partners/envertis-div-of-vision-solutions-pty-ltd-1136565" },
  { name: "Ioppolo & Associates", country: "Australia", tier: "Silver", path: "/partners/ioppolo-associates-194420" },
  { name: "Orcadea", country: "Australia", tier: "Silver", path: "/partners/orcadea-19273406" },
  { name: "Portcities Australia", country: "Australia", tier: "Silver", path: "/partners/portcities-australia-2194479" },
  { name: "Summer Technology Pty Ltd", country: "Australia", tier: "Silver", path: "/partners/summer-technology-pty-ltd-4848523" },
  { name: "Dimension3 System Pty Ltd", country: "Australia", tier: "Silver", path: "/partners/dimension3-system-pty-ltd-11322232" },
  { name: "Atliis 360", country: "Australia", tier: "Silver", path: "/partners/atliis-360-6158346" },
  { name: "NEXEVOLVE PTY LTD", country: "Australia", tier: "Silver", path: "/partners/nexevolve-pty-ltd-28611512" },
  { name: "EnCollab", country: "Australia", tier: "Silver", path: "/partners/encollab-24182825" },
  { name: "Havi Technology", country: "Australia", tier: "Ready", path: "/partners/havi-technology-565083" },
  { name: "MoonSun PTY LTD", country: "Australia", tier: "Ready", path: "/partners/moonsun-pty-ltd-7215113" },
  { name: "ITMS GROUP AUSTRALIA", country: "Australia", tier: "Ready", path: "/partners/itms-group-australia-6516936" },
  { name: "AUBOROS", country: "Australia", tier: "Ready", path: "/partners/auboros-12648683" },
  { name: "Inspired Software Pty Ltd", country: "Australia", tier: "Ready", path: "/partners/inspired-software-pty-ltd-61482" },
  { name: "CORVIO PTY LTD", country: "Australia", tier: "Ready", path: "/partners/corvio-pty-ltd-27890961" },
  { name: "Core One Pty Ltd", country: "Australia", tier: "Ready", path: "/partners/core-one-pty-ltd-21105316" },
  { name: "Dapth Pty Ltd", country: "Australia", tier: "Ready", path: "/partners/dapth-pty-ltd-10235536" },

  // ---------------- France ----------------
  { name: "Apik by OCI", country: "France", tier: "Gold", path: "/partners/apik-by-oci-732280" },
  { name: "IROKOO", country: "France", tier: "Gold", path: "/partners/irokoo-6856840" },
  { name: "Captivea", country: "France", tier: "Gold", path: "/partners/captivea-351158" },
  { name: "Prelium", country: "France", tier: "Gold", path: "/partners/prelium-31876585" },
  { name: "NALIOS FRANCE", country: "France", tier: "Gold", path: "/partners/nalios-france-13868983" },
  { name: "Sudokeys", country: "France", tier: "Gold", path: "/partners/sudokeys-3934501" },
  { name: "Portcities Phidias", country: "France", tier: "Gold", path: "/partners/portcities-phidias-5953324" },
  { name: "Scalizer", country: "France", tier: "Gold", path: "/partners/scalizer-7258166" },
  { name: "DYNAPPS France", country: "France", tier: "Gold", path: "/partners/dynapps-france-23772349" },
  { name: "Falinwa France", country: "France", tier: "Gold", path: "/partners/falinwa-france-301093" },
  { name: "OKTEO", country: "France", tier: "Gold", path: "/partners/okteo-11289165" },
  { name: "Camptocamp France SAS", country: "France", tier: "Gold", path: "/partners/camptocamp-france-sas-15837" },
  { name: "Orbeet", country: "France", tier: "Gold", path: "/partners/orbeet-15366275" },
  { name: "Smile France", country: "France", tier: "Gold", path: "/partners/smile-france-22310792" },
  { name: "DarbTech Labs SAS", country: "France", tier: "Gold", path: "/partners/darbtech-labs-sas-4005278" },
  { name: "Ouiddoo", country: "France", tier: "Silver", path: "/partners/ouiddoo-5579951" },
  { name: "ArkeUp eDoo", country: "France", tier: "Silver", path: "/partners/arkeup-edoo-780745" },
  { name: "ADQUAT", country: "France", tier: "Silver", path: "/partners/adquat-17571" },
  { name: "Subteno", country: "France", tier: "Silver", path: "/partners/subteno-1575833" },
  { name: "NUPROD", country: "France", tier: "Silver", path: "/partners/nuprod-7383767" },

  // ---------------- Belgium ----------------
  { name: "Dynapps NV", country: "Belgium", tier: "Gold", path: "/partners/dynapps-nv-4155" },
  { name: "Somko BV", country: "Belgium", tier: "Gold", path: "/partners/somko-bv-4254310" },
  { name: "Nalios International", country: "Belgium", tier: "Gold", path: "/partners/nalios-international-12935748" },
  { name: "Eezee-it SA", country: "Belgium", tier: "Gold", path: "/partners/eezee-it-sa-5534211" },
  { name: "DPHI sprl", country: "Belgium", tier: "Gold", path: "/partners/dphi-sprl-554730" },
  { name: "dear digital", country: "Belgium", tier: "Gold", path: "/partners/dear-digital-25750815" },
  { name: "tsc - The Service Company SRL", country: "Belgium", tier: "Gold", path: "/partners/tsc-the-service-company-srl-2332308" },
  { name: "Callista", country: "Belgium", tier: "Gold", path: "/partners/callista-785992" },
  { name: "Squareflow S.A.", country: "Belgium", tier: "Gold", path: "/partners/squareflow-s-a-4296072" },
  { name: "Niboo SRL", country: "Belgium", tier: "Gold", path: "/partners/niboo-srl-332882" },
  { name: "Idealis Consulting", country: "Belgium", tier: "Gold", path: "/partners/idealis-consulting--295" },
  { name: "OBS Solutions", country: "Belgium", tier: "Gold", path: "/partners/obs-solutions-5471399" },
  { name: "Obycron", country: "Belgium", tier: "Gold", path: "/partners/obycron-23973897" },
  { name: "Sofatech", country: "Belgium", tier: "Gold", path: "/partners/sofatech-10830707" },
  { name: "Acsone", country: "Belgium", tier: "Gold", path: "/partners/acsone-13425" },
  { name: "Endoo", country: "Belgium", tier: "Gold", path: "/partners/endoo-23380169" },
  { name: "Cloudware NV", country: "Belgium", tier: "Gold", path: "/partners/cloudware-nv-16637852" },
  { name: "Deloitte Consulting & Advisory", country: "Belgium", tier: "Gold", path: "/partners/deloitte-consulting-advisory-4068752" },
  { name: "Accomodata BV", country: "Belgium", tier: "Silver", path: "/partners/accomodata-bv-4989224" },
  { name: "EVATO BV", country: "Belgium", tier: "Silver", path: "/partners/evato-bv-2182652" },

  // ---------------- Brazil ----------------
  { name: "Have Consultoria e Treinamento", country: "Brazil", tier: "Silver", path: "/partners/have-consultoria-e-treinamento-17287622" },
  { name: "Xmarts Brasil", country: "Brazil", tier: "Silver", path: "/partners/xmarts-brasil-12995187" },
  { name: "NETSAC BRAINWAVE TECNOLOGIA DA INFORMACAO LTDA", country: "Brazil", tier: "Silver", path: "/partners/netsac-brainwave-tecnologia-da-informacao-ltda-15299407" },
  { name: "ITL Global Technologies", country: "Brazil", tier: "Silver", path: "/partners/itl-global-technologies-14749004" },
  { name: "ILIOS SISTEMAS LTDA", country: "Brazil", tier: "Silver", path: "/partners/ilios-sistemas-ltda-13773597" },
  { name: "Edoo.me", country: "Brazil", tier: "Ready", path: "/partners/edoo-me-2141215" },
  { name: "ODOX TECNOLOGIA LTDA", country: "Brazil", tier: "Ready", path: "/partners/odox-tecnologia-ltda-12731111" },
  { name: "VSM - Digital Solutions", country: "Brazil", tier: "Ready", path: "/partners/vsm-digital-solutions-14886290" },
  { name: "ALLSS Soluções em Sistemas LTDA", country: "Brazil", tier: "Ready", path: "/partners/allss-solucoes-em-sistemas-ltda-3743176" },
  { name: "OUTVIEW SOLUÇÕES EM TECNOLOGIA", country: "Brazil", tier: "Ready", path: "/partners/outview-solucoes-em-tecnologia-13068008" },
  { name: "IT Brasil", country: "Brazil", tier: "Ready", path: "/partners/it-brasil-2258110" },
  { name: "MULTI MIND CONSULTORIA LTDA", country: "Brazil", tier: "Ready", path: "/partners/multi-mind-consultoria-ltda-20820924" },
  { name: "Ouro Tecnologia", country: "Brazil", tier: "Ready", path: "/partners/ouro-tecnologia-22424227" },
  { name: "SULIVAM SERVICOS DE TECNOLOGIA DA INFORMACAO LTDA", country: "Brazil", tier: "Ready", path: "/partners/sulivam-servicos-de-tecnologia-da-informacao-ltda-26561259" },
  { name: "Softhill", country: "Brazil", tier: "Ready", path: "/partners/softhill-12381008" },
  { name: "Brave IT Serviços", country: "Brazil", tier: "Ready", path: "/partners/brave-it-servicos-14812923" },
  { name: "DanySoft", country: "Brazil", tier: "Ready", path: "/partners/danysoft-21383641" },
  { name: "Deepstrat Serviços LTDA", country: "Brazil", tier: "Ready", path: "/partners/deepstrat-servicos-ltda-32619675" },
  { name: "Ocakit", country: "Brazil", tier: "Ready", path: "/partners/ocakit-16241809" },
  { name: "TAUGA BUSINESS SOLUTIONS INFORMATICA LTDA", country: "Brazil", tier: "Ready", path: "/partners/tauga-business-solutions-informatica-ltda-29959415" },

  // ---------------- Spain ----------------
  { name: "QubiQ 2010, S.L", country: "Spain", tier: "Gold", path: "/partners/qubiq-2010-s-l-1394664" },
  { name: "Nanobytes Informática y Telecomunicaciones S.L.", country: "Spain", tier: "Gold", path: "/partners/nanobytes-informatica-y-telecomunicaciones-s-l-938517" },
  { name: "Process Control Technology SL", country: "Spain", tier: "Gold", path: "/partners/process-control-technology-sl-15337147" },
  { name: "Dynapps ES SL", country: "Spain", tier: "Gold", path: "/partners/dynapps-es-sl-78899" },
  { name: "PUNT SISTEMES SLU", country: "Spain", tier: "Gold", path: "/partners/punt-sistemes-slu-22115" },
  { name: "Consultoría Informática Studio73, S.L.", country: "Spain", tier: "Gold", path: "/partners/consultoria-informatica-studio73-s-l-1506080" },
  { name: "Octupus Technologies SL", country: "Spain", tier: "Gold", path: "/partners/octupus-technologies-sl-3917484" },
  { name: "Grupo Madetosoft S.L.", country: "Spain", tier: "Gold", path: "/partners/grupo-madetosoft-s-l-6521071" },
  { name: "BIRTUM SOLUCIONES, S.L.", country: "Spain", tier: "Gold", path: "/partners/birtum-soluciones-s-l-6534845" },
  { name: "APUNTS INFORMÀTICA I TELECOMUNICACIONS, S.L.", country: "Spain", tier: "Silver", path: "/partners/apunts-informatica-i-telecomunicacions-s-l-2074538" },
  { name: "IPGRUP INNOVATEC, S.L.", country: "Spain", tier: "Silver", path: "/partners/ipgrup-innovatec-s-l-4353862" },
  { name: "LANDOO Sistemas de Información S.L.", country: "Spain", tier: "Silver", path: "/partners/landoo-sistemas-de-informacion-s-l-965780" },
  { name: "INFORMATICA SISTEMES I TECNOLOGIA DIGITAL SL", country: "Spain", tier: "Silver", path: "/partners/informatica-sistemes-i-tecnologia-digital-sl-1532020" },
  { name: "Garber Web Solutions SL", country: "Spain", tier: "Silver", path: "/partners/garber-web-solutions-sl-7059869" },
  { name: "Zeumat Zitycard S.L.", country: "Spain", tier: "Silver", path: "/partners/zeumat-zitycard-s-l-1098556" },
  { name: "MIRANDIR PARTNERS S.R.L", country: "Spain", tier: "Silver", path: "/partners/mirandir-partners-s-r-l-5232548" },
  { name: "Remote Resolution Method Consultoria S.L.", country: "Spain", tier: "Silver", path: "/partners/remote-resolution-method-consultoria-s-l-5137657" },
  { name: "Daruma IT SL", country: "Spain", tier: "Silver", path: "/partners/daruma-it-sl-10976337" },
  { name: "TECNILOOP DIGITAL SERVICES, S.L.", country: "Spain", tier: "Silver", path: "/partners/tecniloop-digital-services-s-l-12724544" },
  { name: "Sistemas Digitales de informática, S.L.", country: "Spain", tier: "Silver", path: "/partners/sistemas-digitales-de-informatica-s-l-7293785" },

  // ---------------- Italy ----------------
  { name: "STeSI Consulting", country: "Italy", tier: "Gold", path: "/partners/stesi-consulting-2649749" },
  { name: "Openforce srl", country: "Italy", tier: "Gold", path: "/partners/openforce-srl-1986856" },
  { name: "Huroos Srl", country: "Italy", tier: "Gold", path: "/partners/huroos-srl-7274999" },
  { name: "DC Engineering", country: "Italy", tier: "Gold", path: "/partners/dc-engineering-5926874" },
  { name: "UNITIVA SRL", country: "Italy", tier: "Gold", path: "/partners/unitiva-srl-5470915" },
  { name: "Digiduu S.r.l.", country: "Italy", tier: "Gold", path: "/partners/digiduu-s-r-l-15891421" },
  { name: "QuickStart2 Srl", country: "Italy", tier: "Silver", path: "/partners/quickstart2-srl-9923744" },
  { name: "A.B.C. srl", country: "Italy", tier: "Silver", path: "/partners/a-b-c-srl-4885615" },
  { name: "EsseTech marchio by DueEsseTi Srl", country: "Italy", tier: "Silver", path: "/partners/essetech-marchio-by-dueesseti-srl-5274566" },
  { name: "Pixora S.r.l.", country: "Italy", tier: "Silver", path: "/partners/pixora-s-r-l-6751254" },
  { name: "BLOOMUP SRL", country: "Italy", tier: "Silver", path: "/partners/bloomup-srl-7400695" },
  { name: "Nexapp S.r.l.", country: "Italy", tier: "Silver", path: "/partners/nexapp-s-r-l-1276126" },
  { name: "Bagubits Srls", country: "Italy", tier: "Silver", path: "/partners/bagubits-srls-6636921" },
  { name: "Foreach SRL", country: "Italy", tier: "Silver", path: "/partners/foreach-srl-13706319" },
  { name: "KeyType Srl", country: "Italy", tier: "Silver", path: "/partners/keytype-srl-13829491" },
  { name: "Ati Comunicazione", country: "Italy", tier: "Silver", path: "/partners/ati-comunicazione-7434170" },
  { name: "B2T S.r.l.", country: "Italy", tier: "Silver", path: "/partners/b2t-s-r-l-7220479" },
  { name: "Digital Automations srl", country: "Italy", tier: "Silver", path: "/partners/digital-automations-srl-4363495" },
  { name: "Webcircles srl", country: "Italy", tier: "Silver", path: "/partners/webcircles-srl-6265148" },
  { name: "Novi Data Srl", country: "Italy", tier: "Silver", path: "/partners/novi-data-srl-1208935" },

  // ---------------- Mexico ----------------
  { name: "Xmarts - Doit Digital", country: "Mexico", tier: "Gold", path: "/partners/xmarts-doit-digital-11037713" },
  { name: "VAUXOO CONSULTORES", country: "Mexico", tier: "Gold", path: "/partners/vauxoo-consultores-20775050" },
  { name: "BIRTUM SOLUCIONES MEXICO", country: "Mexico", tier: "Gold", path: "/partners/birtum-soluciones-mexico-3475357" },
  { name: "MILLORAMEX TECNOLOGIA", country: "Mexico", tier: "Gold", path: "/partners/milloramex-tecnologia-1786702" },
  { name: "GW DIGITAL CONSULTING GROUP", country: "Mexico", tier: "Gold", path: "/partners/gw-digital-consulting-group-11498426" },
  { name: "ASESORES Y SOLUCIONES ANFEPI", country: "Mexico", tier: "Gold", path: "/partners/asesores-y-soluciones-anfepi-2046840" },
  { name: "MORWI ENCODERS CONSULTING", country: "Mexico", tier: "Gold", path: "/partners/morwi-encoders-consulting-2370123" },
  { name: "RAIL CONSULTING", country: "Mexico", tier: "Gold", path: "/partners/rail-consulting-6779540" },
  { name: "EXDOO TI", country: "Mexico", tier: "Gold", path: "/partners/exdoo-ti-6593641" },
  { name: "ALTREGY SOLUTIONS", country: "Mexico", tier: "Gold", path: "/partners/altregy-solutions-17280021" },
  { name: "SFERAZUL", country: "Mexico", tier: "Gold", path: "/partners/sferazul-6460299" },
  { name: "MIT MUT", country: "Mexico", tier: "Gold", path: "/partners/mit-mut-2153122" },
  { name: "SMART BYTE INNOVATION LAB", country: "Mexico", tier: "Silver", path: "/partners/smart-byte-innovation-lab-9097474" },
  { name: "STONES BUSINESS GROUP", country: "Mexico", tier: "Silver", path: "/partners/stones-business-group-11413217" },
  { name: "SOLTEIN", country: "Mexico", tier: "Silver", path: "/partners/soltein-1448675" },
  { name: "SYSERPTEK SOLUTIONS", country: "Mexico", tier: "Silver", path: "/partners/syserptek-solutions-8798717" },
  { name: "NICOLS CONSULTORES", country: "Mexico", tier: "Silver", path: "/partners/nicols-consultores-4729735" },
  { name: "LUIS GERARDO CRUZ GARCIA", country: "Mexico", tier: "Silver", path: "/partners/luis-gerardo-cruz-garcia-13700532" },
  { name: "Humanytek", country: "Mexico", tier: "Silver", path: "/partners/humanytek-600600" },
  { name: "Dataliza", country: "Mexico", tier: "Silver", path: "/partners/dataliza-19561010" },

  // ---------------- Saudi Arabia ----------------
  { name: "Global Solutions", country: "Saudi Arabia", tier: "Gold", path: "/partners/global-solutions-3428807" },
  { name: "Plus Tech Company", country: "Saudi Arabia", tier: "Gold", path: "/partners/plus-tech-company-4700047" },
  { name: "Intelligent Experts Technology (IET)", country: "Saudi Arabia", tier: "Gold", path: "/partners/intelligent-experts-technology-iet-4840227" },
  { name: "Premium Tech", country: "Saudi Arabia", tier: "Gold", path: "/partners/premium-tech-19604425" },
  { name: "OdooTec", country: "Saudi Arabia", tier: "Gold", path: "/partners/odootec-اودوتك-559295" },
  { name: "TeleNoc", country: "Saudi Arabia", tier: "Gold", path: "/partners/telenoc-هلكون-لتقنية-المعلومات-465426" },
  { name: "Prof Business", country: "Saudi Arabia", tier: "Gold", path: "/partners/prof-business-4398722" },
  { name: "Al Majal Tech", country: "Saudi Arabia", tier: "Gold", path: "/partners/al-majal-tech-16511064" },
  { name: "Peerless - KSA", country: "Saudi Arabia", tier: "Gold", path: "/partners/peerless-ksa-2137773" },
  { name: "NAQLAH Technologies", country: "Saudi Arabia", tier: "Gold", path: "/partners/naqlah-technologies-5571223" },
  { name: "Centione Arabia", country: "Saudi Arabia", tier: "Gold", path: "/partners/centione-arabia-عرين-الحلول-لتقنية-نظم-المعلومات-11503192" },
  { name: "Palmate Technologies", country: "Saudi Arabia", tier: "Gold", path: "/partners/palmate-technologies-929611" },
  { name: "Machinser Group - Alafkar Almotlaqa", country: "Saudi Arabia", tier: "Gold", path: "/partners/machinser-group-alafkar-almotlaqa-7857166" },
  { name: "Masa", country: "Saudi Arabia", tier: "Gold", path: "/partners/masa-الشركة-العربية-المتخصصة-للاستشارات-وتقنية-المعلومات-988848" },
  { name: "Upward Technologies", country: "Saudi Arabia", tier: "Gold", path: "/partners/upward-technologies-6482438" },
  { name: "Ideal Lines Computer Systems (iLines)", country: "Saudi Arabia", tier: "Gold", path: "/partners/ideal-lines-computer-systems-ilines-13592904" },
  { name: "Digital Harbor", country: "Saudi Arabia", tier: "Gold", path: "/partners/digital-harbor-ديجيتال-هاربر-10222849" },
  { name: "Era Group LTD. CO", country: "Saudi Arabia", tier: "Gold", path: "/partners/era-group-ltd-co-3044647" },
  { name: "Intiqaal Information Technology", country: "Saudi Arabia", tier: "Gold", path: "/partners/intiqaal-information-technology-12615984" },
  { name: "Variety IT", country: "Saudi Arabia", tier: "Gold", path: "/partners/variety-it-14998669" },

  // ---------------- Egypt ----------------
  { name: "RoayaTec", country: "Egypt", tier: "Gold", path: "/partners/roayatec-17207720" },
  { name: "IT SYS Corporation", country: "Egypt", tier: "Gold", path: "/partners/it-sys-corporation-167908" },
  { name: "ZAD Solutions", country: "Egypt", tier: "Gold", path: "/partners/zad-solutions-527787" },
  { name: "OIT Solutions", country: "Egypt", tier: "Gold", path: "/partners/oit-solutions-4196398" },
  { name: "Knowledge BI", country: "Egypt", tier: "Gold", path: "/partners/knowledge-bi-4051443" },
  { name: "Perfect-tech", country: "Egypt", tier: "Gold", path: "/partners/perfect-tech-5647202" },
  { name: "RIGHTECHS Solutions", country: "Egypt", tier: "Gold", path: "/partners/rightechs-solutions-1825301" },
  { name: "CDS Solutions", country: "Egypt", tier: "Gold", path: "/partners/cds-solutions-4990756" },
  { name: "KamahTech", country: "Egypt", tier: "Gold", path: "/partners/kamahtech-2123356" },
  { name: "Top Business", country: "Egypt", tier: "Gold", path: "/partners/top-business-1314088" },
  { name: "Archer Solutions", country: "Egypt", tier: "Gold", path: "/partners/archer-solutions-1029333" },
  { name: "New Tech Software NTS", country: "Egypt", tier: "Gold", path: "/partners/new-tech-software-nts-2407246" },
  { name: "Diamond Vision (DVIT)", country: "Egypt", tier: "Gold", path: "/partners/diamond-vision-dvit-22570994" },
  { name: "Tarabut", country: "Egypt", tier: "Gold", path: "/partners/tarabut-1949475" },
  { name: "QSYS", country: "Egypt", tier: "Gold", path: "/partners/qsys-9702768" },
  { name: "CORE-BPO", country: "Egypt", tier: "Gold", path: "/partners/core-bpo-14447" },
  { name: "TDS - Talents Digital Services", country: "Egypt", tier: "Gold", path: "/partners/tds-talents-digital-services-10173977" },
  { name: "Softobia", country: "Egypt", tier: "Gold", path: "/partners/softobia-19927323" },
  { name: "HNG Business Solutions", country: "Egypt", tier: "Silver", path: "/partners/hng-business-solutions-15240208" },
  { name: "Concept Solutions - EG", country: "Egypt", tier: "Silver", path: "/partners/concept-solutions-eg-7169707" },
];

PARTNERS.forEach(p => { p.url = "https://www.odoo.com" + encodeURI(p.path); });

// Country SEO blurbs: short, original descriptions (not copied from Odoo)
// shown on the directory page for search-engine content and reader context.
const COUNTRY_INFO = {
  "India": "India has one of the largest Odoo implementation markets in the world, with well over a hundred certified partners. Demand is driven by SMEs and mid-market manufacturers, trading companies, and IT services firms adopting Odoo as an affordable alternative to SAP or Oracle. Many Indian partners also serve international clients remotely, so pricing and time-zone overlap are worth checking alongside certification tier.",
  "United States": "The US Odoo partner network spans small boutique consultancies to larger regional integrators, often specializing by industry (retail, manufacturing, field service) or by Odoo module (inventory, accounting, e-commerce). Because the market is large and geographically spread, it's common to work with a partner remotely rather than requiring someone in the same state.",
  "United Kingdom": "UK-based Odoo partners typically serve SMEs needing UK-specific accounting, VAT, and payroll localization alongside core ERP rollout. The partner base is smaller than the US or India, so Gold partners here tend to have deep, long-standing experience across many client sectors.",
  "Germany": "Germany's Odoo partner ecosystem is heavily weighted toward GmbH-structured consultancies with strong manufacturing and logistics sector experience, reflecting the country's industrial base. German partners frequently handle DATEV accounting integration and GoBD-compliant record keeping as part of implementations.",
  "United Arab Emirates": "The UAE has a fast-growing Odoo partner market concentrated in Dubai and the free zones, serving trading, logistics, retail, and real estate businesses across the wider Gulf region. Many partners here also support clients in Saudi Arabia and other GCC countries from a single UAE base.",
  "Canada": "Canadian Odoo partners are split between francophone firms serving Quebec (with French-language and provincial tax requirements) and English-speaking partners elsewhere, plus several cross-border firms also licensed to work in the US.",
  "Netherlands": "Dutch Odoo partners are known for strong technical depth and several have grown into partners with operations across multiple European countries. The market favors partners who can handle both ERP implementation and custom module development in-house.",
  "Australia": "Australian Odoo partners mostly serve small and mid-sized businesses in retail, trades, and professional services, with a strong base in the WilldooIT-style specialist consultancy model rather than large generalist integrators. BAS/GST compliance support is a common ask during implementation.",
  "France": "France has one of Europe's largest and most mature Odoo partner networks, partly because Odoo itself was founded there. French partners range from large multi-office integrators like Camptocamp and Smile to specialist boutiques, and many offer bilingual (French/English) implementation support.",
  "Belgium": "As Odoo's home country, Belgium has an unusually dense and experienced partner network relative to its size, including partners that have grown into international groups. Belgian partners often have the earliest access to new Odoo features and modules.",
  "Brazil": "Brazil's Odoo partner market is still developing relative to its economy size, which means partners here often wear multiple hats (implementation, training, and ongoing support) for each client. Brazilian tax complexity (NF-e, ICMS) makes local implementation expertise especially important versus using an international partner.",
  "Spain": "Spain has a broad, well-established Odoo partner base covering most regions, often with strong sector focus in retail, hospitality, and professional services. Many Spanish partners also support Spanish-speaking clients in Latin America remotely.",
  "Italy": "Italian Odoo partners frequently specialize by industry vertical (manufacturing, fashion/retail, food & beverage) and handle Italy-specific invoicing (fatturazione elettronica) requirements as a standard part of implementation projects.",
  "Mexico": "Mexico has one of Latin America's largest Odoo partner networks, shaped heavily by the country's CFDI electronic invoicing mandate, which most local partners build into every implementation from day one.",
  "Saudi Arabia": "Saudi Arabia's Odoo partner market has grown quickly alongside the country's digital transformation push, with partners commonly handling ZATCA e-invoicing compliance and Arabic-language localization as core parts of any rollout.",
  "Egypt": "Egypt has emerged as a major regional hub for Odoo implementation talent, with partners serving both the domestic market and clients across the wider Middle East and Africa, often at competitive rates relative to Gulf-based firms.",
};
